### ISSUE TITLE
Timeout issues

### ISSUE THREAD

**Issue by dometto** [UtrechtUniversity/SRC-catalog-items#2]
We are running into timeout issues in the molecule test, especially when doing large apt installs on multiple targets (focal and jammy) at the same time. Investigate ways to improve this:

* tweak molecule timeout settings
* deploy on different platform
  * own github runners
  * directly on SRC
  * via our own build server (travis?)
 * run builds at the different times

**Comment by joaomarcosjova** [comment]
To address the timeout issues in the Molecule test, especially during large `apt` installs on multiple targets, several strategies can be considered:

1. **Tweak Molecule Timeout Settings**: Adjust the timeout settings in the Molecule configuration file (`molecule.yml`). You can increase the timeout value for tasks that are known to take longer, such as package installation.

   Example:
   ```yaml
   provisioner:
     name: ansible
     lint: |
       /usr/bin/ansible-lint
     log: true
     lint_skip_list: |
       - ANSIBLE0012
   platforms:
     - name: instance
       box: ubuntu/focal64
       memory: 2048
       # Increase timeout for apt installs
       provision_timeout: 300
   ```

2. **Deploy on Different Platforms**: If your tests are running on virtual machines or containers, consider deploying them on different platforms. For example, you can use different cloud providers like AWS, GCP, or Azure to distribute the load and potentially reduce timeouts.

3. **Own GitHub Runners**: Utilize your organization's own GitHub runners instead of relying on GitHub's shared runners. This allows you to have more control over the resources available for running tests and reduces contention with other GitHub users.

4. **Directly on Source Control Repositories (SRC)**: Run the tests directly on the source control repositories, especially if your organization hosts its code repositories internally. This can minimize network latency and improve test execution times.

5. **Own Build Server (Travis, Jenkins, etc.)**: Set up your own build server using tools like Travis CI, Jenkins, or GitLab CI. This gives you full control over the build environment and allows you to optimize resource allocation based on your requirements.

6. **Run Builds at Different Times**: Schedule the builds to run at different times to avoid peak load periods. This can help distribute the load more evenly and reduce contention for shared resources.

To implement these strategies, you'll need to adjust your CI/CD pipeline configuration, Molecule settings, and possibly infrastructure provisioning scripts. Experiment with different approaches to find the best solution for your specific use case and infrastructure constraints.
